# Generated by Django 5.0.1 on 2024-01-29 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzduotis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzduotis',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 8, 36, 19, 423904), verbose_name='Data'),
        ),
    ]
