# Generated by Django 5.0.1 on 2024-01-29 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzduotis', '0003_alter_uzduotis_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 9, 4, 26, 281741, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
