# Generated by Django 5.0.1 on 2024-01-29 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzduotis', '0004_alter_uzduotis_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
