# Generated by Django 5.0.1 on 2024-01-29 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzduotis', '0005_alter_uzduotis_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
    ]
