# Generated by Django 5.0.1 on 2024-01-29 12:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzduotis', '0008_alter_uzduotis_uzduoties_tekstas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='uzduoties_tekstas',
            field=tinymce.models.HTMLField(verbose_name='Užduotis'),
        ),
    ]
